# Load Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
%matplotlib inline
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, cohen_kappa_score

# Import data

In [2]:
df=pd.read_csv('crime 2.csv')
df=pd.read_csv('crime 2.csv')


In [3]:
df.head(10)

REGION  GARDA DIVISION  OFFENCE CODE  \
0  NORTHERN REGION  CAVAN/MONAGHAN           111   
1  NORTHERN REGION  CAVAN/MONAGHAN           112   
2  NORTHERN REGION  CAVAN/MONAGHAN           113   
3  NORTHERN REGION  CAVAN/MONAGHAN            12   
4  NORTHERN REGION  CAVAN/MONAGHAN            21   
5  NORTHERN REGION  CAVAN/MONAGHAN            22   
6  NORTHERN REGION  CAVAN/MONAGHAN           311   
7  NORTHERN REGION  CAVAN/MONAGHAN           312   
8  NORTHERN REGION  CAVAN/MONAGHAN            33   
9  NORTHERN REGION  CAVAN/MONAGHAN            34   

                              OFFENCE  \
0                              Murder   
1                        Manslaughter   
2                         Infanticide   
3  Dangerous driving leading to death   
4             Rape and sexual assault   
5               Other sexual offences   
6                      Murder-attempt   
7                       Murder-threat   
8     Harassment and related offences   
9     Assault causing harm/ poisoning   

                                     TYPE OF OFFENCE  2003Q1  2003Q2  2003Q3  \
0                                  HOMICIDE OFFENCES       0       0       0   
1                                  HOMICIDE OFFENCES       0       0       0   
2                                  HOMICIDE OFFENCES       0       0       0   
3                                  HOMICIDE OFFENCES       1       0       1   
4                                    SEXUAL OFFENCES      24      15       5   
5                                    SEXUAL OFFENCES       0       0       0   
6  ATTEMPTS/THREATS TO MURDER/ASSAULTS/ HARASSMEN...       0       0       0   
7  ATTEMPTS/THREATS TO MURDER/ASSAULTS/ HARASSMEN...       0       0       0   
8  ATTEMPTS/THREATS TO MURDER/ASSAULTS/ HARASSMEN...      13       5      19   
9  ATTEMPTS/THREATS TO MURDER/ASSAULTS/ HARASSMEN...      21      32      35   

   2003Q4  2004Q1  ...  2017Q2  2017Q3  2017Q4  2018Q1  2018Q2  2018Q3  \
0       0       0  ...       0       0       1       0       0       1   
1       0       0  ...       0       0       0       1       0       0   
2       0       0  ...       0       0       0       0       0       0   
3       0       0  ...       1       1       1       0       0       0   
4       5      14  ...      16       8      14      23      21      13   
5       0       0  ...       1       1       1       0       2       3   
6       0       0  ...       0       0       0       0       0       0   
7       0       0  ...       9      10      10       6       9       8   
8      11      16  ...      15      11      19      19      16      15   
9      44      28  ...      52      39      60      49      65      62   

   2018Q4  2019Q1  2019Q2  2019Q3  
0       0       0       0       0  
1       1       0       0       0  
2       0       0       0       0  
3       1       0       0       0  
4      23      19      20      17  
5       2       8       1       8  
6       0       0       0       0  
7      12      13      13      15  
8      11      12      19      18  
9      62      63      49      46  

[10 rows x 72 columns]

In [4]:
df.isnull().sum()

REGION             0
GARDA DIVISION     0
OFFENCE CODE       0
OFFENCE            0
TYPE OF OFFENCE    0
                  ..
2018Q3             0
2018Q4             0
2019Q1             0
2019Q2             0
2019Q3             0
Length: 72, dtype: int64

In [5]:
df.dtypes

REGION             object
GARDA DIVISION     object
OFFENCE CODE        int64
OFFENCE            object
TYPE OF OFFENCE    object
                    ...  
2018Q3              int64
2018Q4              int64
2019Q1              int64
2019Q2              int64
2019Q3              int64
Length: 72, dtype: object

# Label Encoder

In [6]:
df['OFFENCE'].unique()

array(['Murder', 'Manslaughter', 'Infanticide',
       'Dangerous driving leading to death', 'Rape and sexual assault',
       'Other sexual offences', 'Murder-attempt', 'Murder-threat',
       'Harassment and related offences',
       'Assault causing harm/ poisoning', 'Other assault',
       'Dangerous driving causing serious bodily harm',
       'Driving/in charge of a vehicle while over legal alcohol limit',
       'Driving/in charge of a vehicle under the influence of drugs',
       'Endangerment with potential for serious harm/death',
       'Abandoning a child/ child neglect and cruelty',
       'Unseaworthy/dangerous use of boat or ship',
       'False alarm/interference with aircraft or air transport facilities',
       'Endangering traffic offences', 'False imprisonment',
       'Abduction of person under 16 years of age',
       'Human trafficking offences',
       'Robbery of an establishment or institution',
       'Robbery of cash or goods in transit', 'Robbery from the p

In [7]:
lbl_encode=LabelEncoder()
df['REGION']=lbl_encode.fit_transform(df['REGION'])
df['GARDA DIVISION']=lbl_encode.fit_transform(df['GARDA DIVISION'])
df['OFFENCE']=lbl_encode.fit_transform(df['OFFENCE'])
df['TYPE OF OFFENCE']=lbl_encode.fit_transform(df['TYPE OF OFFENCE'])


In [8]:
df

REGION  GARDA DIVISION  OFFENCE CODE  OFFENCE  TYPE OF OFFENCE  2003Q1  \
0          2               0           111       30                6       0   
1          2               0           112       29                6       0   
2          2               0           113       26                6       0   
3          2               0            12       11                6       1   
4          2               0            21       47               11      24   
...      ...             ...           ...      ...              ...     ...   
1619       0              10           136       52                9       8   
1620       0              10           151       33                8       3   
1621       0              10           152       36                8       0   
1622       0              10           153       41                8       2   
1623       0              10           157       34                8     134   

      2003Q2  2003Q3  2003Q4  2004Q1  ...  2017Q2  2017Q3  2017Q4  2018Q1  \
0          0       0       0       0  ...       0       0       1       0   
1          0       0       0       0  ...       0       0       0       1   
2          0       0       0       0  ...       0       0       0       0   
3          0       1       0       0  ...       1       1       1       0   
4         15       5       5      14  ...      16       8      14      23   
...      ...     ...     ...     ...  ...     ...     ...     ...     ...   
1619       5       6       6       7  ...       8       5       3      10   
1620       0       0       7       0  ...       2       3       0       2   
1621       0       0       0       1  ...       1       0       0       1   
1622       1       0       1       2  ...       1       2       1       0   
1623     102     128     116     121  ...     280     318     308     410   

      2018Q2  2018Q3  2018Q4  2019Q1  2019Q2  2019Q3  
0          0       1       0       0       0       0  
1          0       0       1       0       0       0  
2          0       0       0       0       0       0  
3          0       0       1       0       0       0  
4         21      13      23      19      20      17  
...      ...     ...     ...     ...     ...     ...  
1619       4       5       5       6      16       9  
1620       0       0       2       5       4       5  
1621       0       0       0       0       0       1  
1622       1       0       0       0       1       0  
1623     447     393     455     437     417     305  

[1624 rows x 72 columns]

In [9]:
lbl_encode=LabelEncoder()
lbl_encode.fit_transform(df['REGION'])

array([2, 2, 2, ..., 0, 0, 0], dtype=int64)

In [10]:
lbl_encode=LabelEncoder()
lbl_encode.fit_transform(df['GARDA DIVISION'])

array([ 0,  0,  0, ..., 10, 10, 10], dtype=int64)

In [11]:
lbl_encode=LabelEncoder()
lbl_encode.fit_transform(df['OFFENCE'])

array([30, 29, 26, ..., 36, 41, 34], dtype=int64)

In [12]:
lbl_encode=LabelEncoder()
lbl_encode.fit_transform(df['TYPE OF OFFENCE'])

array([6, 6, 6, ..., 8, 8, 8], dtype=int64)

In [13]:
df.head()

REGION  GARDA DIVISION  OFFENCE CODE  OFFENCE  TYPE OF OFFENCE  2003Q1  \
0       2               0           111       30                6       0   
1       2               0           112       29                6       0   
2       2               0           113       26                6       0   
3       2               0            12       11                6       1   
4       2               0            21       47               11      24   

   2003Q2  2003Q3  2003Q4  2004Q1  ...  2017Q2  2017Q3  2017Q4  2018Q1  \
0       0       0       0       0  ...       0       0       1       0   
1       0       0       0       0  ...       0       0       0       1   
2       0       0       0       0  ...       0       0       0       0   
3       0       1       0       0  ...       1       1       1       0   
4      15       5       5      14  ...      16       8      14      23   

   2018Q2  2018Q3  2018Q4  2019Q1  2019Q2  2019Q3  
0       0       1       0       0       0       0  
1       0       0       1       0       0       0  
2       0       0       0       0       0       0  
3       0       0       1       0       0       0  
4      21      13      23      19      20      17  

[5 rows x 72 columns]

# Test and Split

In [14]:
x=df.drop("OFFENCE",axis=1)
y=df["OFFENCE"]

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

print(len(y_train))
print(len(y_test))


1299
325


# Decision Tree Classifier

In [29]:
from sklearn import tree
dt_clf=tree.DecisionTreeClassifier(max_depth=5)

dt_clf.fit(x_train, y_train)
dt_clf.score(x_test, y_test)

y_pred= dt_clf.predict(x_test)
dt_clf.score(x_test, y_test)


0.17846153846153845

In [17]:
#Accuracy= accuracy_score(y_test, y_pred) 
#Kappa= cohen_kappa_score(y_test, y_pred)
#Accuracy, Kappa

In [18]:
#y_pred= dt_clf.predict(x_test)
#from sklearn.metrics import confusion_matrix
#confusion_matrix(y_test, y_pred)

In [19]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold Cross validation

In [20]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dt_clf, x, y, cv=10)
scores

array([0.14723926, 0.14723926, 0.17791411, 0.17791411, 0.16666667,
       0.16666667, 0.18518519, 0.18518519, 0.22839506, 0.22839506])

In [21]:
print(np.mean(scores))

0.18108005756267515


In [22]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 3.4831888675689697


In [23]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# Stratified Cross Validation

In [24]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(dt_clf, x,y, cv=skfold)


In [25]:
print(np.mean(outcome))

0.1804665606301598


In [26]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 6.544622898101807


In [27]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# Repeated Random Train-Test Splits

In [28]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(dt_clf,x,y,cv=ssplit)

In [29]:
results

array([0.16393443, 0.18647541, 0.17418033, 0.16803279, 0.19877049,
       0.20491803, 0.10245902, 0.15368852, 0.19467213, 0.10655738])

In [30]:
print(np.mean(results))

0.1653688524590164


In [31]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 7.023994445800781


In [32]:
#from sklearn.model_selection import cross_val_predict
#pred= cross_val_predict(dt_clf, x_test, y_test)
#pred

In [33]:
#scores_test = cross_val_score(dt_clf, x, y, scoring='r2', cv=10)
#scores_test

In [34]:
#print(np.mean(scores_test))

In [35]:
#from sklearn.metrics import confusion_matrix
#print(classification_report(y_test, y_pred))

# Random Forest Classifier

In [36]:
from sklearn import ensemble
rf_clf= ensemble.RandomForestClassifier(n_estimators=100)
rf_clf.fit(x_train, y_train)
rf_clf.score(x_train, y_train)

1.0

In [37]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold Cross validation

In [38]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(rf_clf, x, y, cv=10)
scores

array([0.85889571, 0.87730061, 0.88343558, 0.82822086, 0.87037037,
       0.90123457, 0.93209877, 0.9382716 , 0.69753086, 0.7962963 ])

In [39]:
print(np.mean(scores))

0.8583655229871999


In [40]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 22.145835161209106


In [41]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# Stratified Cross Validation

In [42]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(rf_clf, x,y, cv=skfold)


In [43]:
print(np.mean(outcome))

0.8596076649246385


In [44]:
outcome

array([0.85889571, 0.88343558, 0.85889571, 0.83435583, 0.88888889,
       0.91358025, 0.93209877, 0.9382716 , 0.66666667, 0.82098765])

In [45]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 28.801300287246704


In [46]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# Repeated Random Train-Test Splits

In [47]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(rf_clf,x,y,cv=ssplit)

In [48]:
results

array([0.80942623, 0.82377049, 0.81967213, 0.83401639, 0.79098361,
       0.82786885, 0.87090164, 0.8442623 , 0.82786885, 0.83811475])

In [49]:
print(np.mean(results))

0.8286885245901641


In [50]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 37.220014333724976


# Naive Bayes Classifier

In [51]:
from sklearn.naive_bayes import GaussianNB
nb_clf= GaussianNB()
nb_clf.fit(x_train, y_train)
nb_clf.score(x_train, y_train)

1.0

In [52]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold Cross validation

In [53]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(nb_clf, x, y, cv=10)
scores

array([1.        , 0.98159509, 1.        , 1.        , 0.98148148,
       1.        , 0.99382716, 0.98148148, 0.90123457, 0.9691358 ])

In [54]:
print(np.mean(scores))

0.9808755585851701


In [55]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 2.4215495586395264


In [56]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# Stratified Cross Validation

In [57]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(nb_clf, x,y, cv=skfold)


In [58]:
print(np.mean(outcome))

0.9808755585851701


In [59]:
outcome

array([1.        , 0.98159509, 1.        , 1.        , 0.98148148,
       1.        , 0.99382716, 0.98148148, 0.90123457, 0.9691358 ])

In [60]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 4.029627799987793


In [61]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# Repeated Random Train-Test Splits

In [62]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(nb_clf,x,y,cv=ssplit)

In [63]:
results

array([0.96721311, 0.95491803, 0.95491803, 0.96721311, 0.95696721,
       0.97540984, 0.97131148, 0.95696721, 0.95901639, 0.97336066])

In [64]:
print(np.mean(results))

0.9637295081967213


In [65]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 3.8601560592651367


In [66]:
#from sklearn import ensemble
#rf_clf= ensemble.RandomForestClassifier(n_estimators=100)
#rf_clf.fit(x_train, y_train)
#rf_clf.score(x_train, y_train)

In [67]:
#from sklearn.model_selection import cross_val_score
#scores = cross_val_score(rf_clf, x, y, scoring='r2', cv=10)
#scores

In [68]:
#print(np.mean(scores))

In [69]:
#from sklearn.naive_bayes import GaussianNB
#nb_clf= GaussianNB()
#nb_clf.fit(x_train, y_train)
#nb_clf.score(x_train, y_train)

In [70]:
#from sklearn.model_selection import cross_val_score
#scores = cross_val_score(nb_clf, x, y, scoring='r2', cv=10)
#scores

In [71]:
#print(np.mean(scores))

# K-Nearest Neighbour Classifier

In [72]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf= KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(x_train, y_train)
knn_clf.score(x_train, y_train)

0.852963818321786

In [73]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold Cross validation

In [74]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(knn_clf, x, y, cv=10)
scores

array([0.7791411 , 0.82822086, 0.7607362 , 0.63803681, 0.74691358,
       0.81481481, 0.80864198, 0.85185185, 0.64814815, 0.70987654])

In [75]:
print(np.mean(scores))

0.7586381882905401


In [76]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 3.0029032230377197


In [77]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# Stratified Cross Validation

In [78]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(knn_clf, x,y, cv=skfold)


In [79]:
print(np.mean(outcome))

0.7586381882905401


In [80]:
outcome

array([0.7791411 , 0.82822086, 0.7607362 , 0.63803681, 0.74691358,
       0.81481481, 0.80864198, 0.85185185, 0.64814815, 0.70987654])

In [81]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 4.391996383666992


In [82]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# Repeated Random Train-Test Splits

In [83]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(knn_clf,x,y,cv=ssplit)

In [84]:
results

array([0.70491803, 0.76229508, 0.69057377, 0.75819672, 0.7397541 ,
       0.73360656, 0.70696721, 0.72131148, 0.69672131, 0.7192623 ])

In [85]:
print(np.mean(results))

0.7233606557377049


In [86]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 14.077925443649292


# Logistic Regression Classifier

In [87]:
from sklearn.linear_model import LogisticRegression
lr_clf= LogisticRegression()
lr_clf.fit(x_train, y_train)
lr_clf.score(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.6043110084680523

In [88]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold Cross validation

In [89]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(lr_clf, x, y, cv=10)
scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.44171779, 0.50920245, 0.57668712, 0.44785276, 0.54938272,
       0.62962963, 0.55555556, 0.61111111, 0.28395062, 0.43209877])

In [90]:
print(np.mean(scores))

0.5037188517761115


In [91]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 29.022860050201416


In [92]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# Stratified Cross Validation

In [93]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(lr_clf, x,y, cv=skfold)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [94]:
print(np.mean(outcome))

0.5037188517761115


In [95]:
outcome

array([0.44171779, 0.50920245, 0.57668712, 0.44785276, 0.54938272,
       0.62962963, 0.55555556, 0.61111111, 0.28395062, 0.43209877])

In [96]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 32.03660178184509


In [97]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# Repeated Random Train-Test Splits

In [98]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(lr_clf,x,y,cv=ssplit)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [99]:
results

array([0.42827869, 0.47131148, 0.45491803, 0.49385246, 0.47540984,
       0.43852459, 0.48360656, 0.45696721, 0.44262295, 0.45286885])

In [100]:
print(np.mean(results))

0.45983606557377055


In [101]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 50.72613167762756
