# Load Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
%matplotlib inline
from sklearn.metrics import accuracy_score, cohen_kappa_score
from sklearn.model_selection import StratifiedKFold

# Import data

In [2]:
df=pd.read_csv('crime 1.csv')
df=pd.read_csv('crime 1.csv')


In [3]:
df.head(10)

incident_id    offense_id  OFFENSE_CODE  OFFENSE_CODE_EXTENSION  \
0  2.022600e+10  2.022600e+16          2999                       0   
1  2.022332e+07  2.022330e+13          2999                       0   
2  2.022309e+07  2.022310e+13          2999                       0   
3  2.022400e+07  2.022400e+13          2999                       0   
4  2.022396e+07  2.022400e+13          2999                       0   
5  2.022390e+07  2.022390e+13          2999                       0   
6  2.022390e+07  2.022390e+13          2999                       0   
7  2.022389e+07  2.022390e+13          2999                       0   
8  2.022808e+07  2.022810e+13          2999                       0   
9  2.022456e+07  2.022460e+13          2999                       0   

           OFFENSE_TYPE_ID OFFENSE_CATEGORY_ID FIRST_OCCURRENCE_DATE  \
0  criminal-mischief-other     public-disorder      01-04-2022 11:30   
1  criminal-mischief-other     public-disorder      01-03-2022 06:45   
2  criminal-mischief-other     public-disorder      01-03-2022 01:00   
3  criminal-mischief-other     public-disorder      01-03-2022 19:47   
4  criminal-mischief-other     public-disorder      01-03-2022 17:06   
5  criminal-mischief-other     public-disorder      01-03-2022 16:40   
6  criminal-mischief-other     public-disorder      01-03-2022 16:19   
7  criminal-mischief-other     public-disorder      01-03-2022 16:15   
8  criminal-mischief-other     public-disorder      01-05-2022 19:00   
9  criminal-mischief-other     public-disorder      01-04-2022 04:30   

  LAST_OCCURRENCE_DATE     REPORTED_DATE  \
0     01-04-2022 12:00  01-04-2022 20:36   
1                  NaN  01-03-2022 11:01   
2                  NaN  01-03-2022 06:11   
3                  NaN  01-03-2022 21:12   
4                  NaN  01-03-2022 20:31   
5                  NaN  01-03-2022 19:07   
6                  NaN  01-03-2022 16:21   
7                  NaN  01-03-2022 23:05   
8     01-06-2022 07:00  01-06-2022 09:03   
9     01-04-2022 04:40  01-04-2022 05:09   

                                    INCIDENT_ADDRESS      GEO_X      GEO_Y  \
0  128 S CANOSA CT                               ...  3135366.0  1685410.0   
1  650 15TH ST                                   ...  3142454.0  1696151.0   
2  919 E COLFAX AVE                              ...  3147484.0  1694898.0   
3  2345 W ALAMEDA AVE                            ...  3136478.0  1684414.0   
4  7800 E SMITH RD                               ...  3169237.0  1705800.0   
5  857 E COLFAX AVE                              ...  3147195.0  1695029.0   
6  1501 S COLORADO BLVD                          ...  3157325.0  1676368.0   
7  1133 N LINCOLN ST                             ...  3144418.0  1692850.0   
8  2500 E CHERRY CREEK S DR                      ...  3152806.0  1685804.0   
9  620 N SANTA FE DR                             ...  3141081.0  1689737.0   

      GEO_LON    GEO_LAT  DISTRICT_ID  PRECINCT_ID     NEIGHBORHOOD_ID  \
0 -105.018825  39.714268          4.0        411.0            valverde   
1 -104.993418  39.743649          6.0        611.0                 cbd   
2 -104.975557  39.740130          6.0        621.0  north-capitol-hill   
3 -105.014892  39.711518          4.0        411.0            valverde   
4 -104.897950  39.769688          5.0        512.0        central-park   
5 -104.976582  39.740495          6.0        621.0  north-capitol-hill   
6 -104.940969  39.689101          3.0        312.0        cory-merrill   
7 -104.986500  39.734556          6.0        623.0        capitol-hill   
8 -104.956826  39.715080          3.0        311.0             belcaro   
9 -104.998426  39.726062          1.0        123.0        lincoln-park   

   IS_CRIME  IS_TRAFFIC  
0         1           0  
1         1           0  
2         1           0  
3         1           0  
4         1           0  
5         1           0  
6         1           0  
7         1           0  
8         1           0  
9         

In [4]:
df.isnull().sum()

incident_id                    0
offense_id                     0
OFFENSE_CODE                   0
OFFENSE_CODE_EXTENSION         0
OFFENSE_TYPE_ID                0
OFFENSE_CATEGORY_ID            0
FIRST_OCCURRENCE_DATE          0
LAST_OCCURRENCE_DATE      303919
REPORTED_DATE                  0
INCIDENT_ADDRESS           38901
GEO_X                       4179
GEO_Y                       4179
GEO_LON                     4180
GEO_LAT                     4180
DISTRICT_ID                    1
PRECINCT_ID                    1
NEIGHBORHOOD_ID                1
IS_CRIME                       0
IS_TRAFFIC                     0
dtype: int64

In [5]:
new_df= df.fillna(0)
new_df

incident_id    offense_id  OFFENSE_CODE  OFFENSE_CODE_EXTENSION  \
0       2.022600e+10  2.022600e+16          2999                       0   
1       2.022332e+07  2.022330e+13          2999                       0   
2       2.022309e+07  2.022310e+13          2999                       0   
3       2.022400e+07  2.022400e+13          2999                       0   
4       2.022396e+07  2.022400e+13          2999                       0   
...              ...           ...           ...                     ...   
486881  2.022211e+09  2.022210e+15          2501                       0   
486882  2.022211e+09  2.022210e+15          2604                       1   
486883  2.022212e+09  2.022210e+15          2605                       0   
486884  2.022601e+10  2.022600e+16          2605                       0   
486885  2.022211e+09  2.022210e+15          2607                       0   

                     OFFENSE_TYPE_ID OFFENSE_CATEGORY_ID  \
0            criminal-mischief-other     public-disorder   
1            criminal-mischief-other     public-disorder   
2            criminal-mischief-other     public-disorder   
3            criminal-mischief-other     public-disorder   
4            criminal-mischief-other     public-disorder   
...                              ...                 ...   
486881                forgery-checks  white-collar-crime   
486882  fraud-criminal-impersonation  white-collar-crime   
486883       theft-unauth-use-of-ftd  white-collar-crime   
486884       theft-unauth-use-of-ftd  white-collar-crime   
486885            fraud-by-telephone  white-collar-crime   

        FIRST_OCCURRENCE_DATE  LAST_OCCURRENCE_DATE          REPORTED_DATE  \
0            01-04-2022 11:30      01-04-2022 12:00       01-04-2022 20:36   
1            01-03-2022 06:45                     0       01-03-2022 11:01   
2            01-03-2022 01:00                     0       01-03-2022 06:11   
3            01-03-2022 19:47                     0       01-03-2022 21:12   
4            01-03-2022 17:06                     0       01-03-2022 20:31   
...                       ...                   ...                    ...   
486881   4/27/2022 1:00:00 PM                     0   4/28/2022 1:34:00 PM   
486882  6/16/2021 12:00:00 AM      02-03-2022 23:59   4/28/2022 3:10:00 PM   
486883   4/23/2022 6:30:00 PM                     0   4/28/2022 3:56:00 PM   
486884   4/27/2022 7:42:00 PM  4/27/2022 7:42:00 PM  4/27/2022 10:28:00 PM   
486885   4/26/2022 1:29:00 PM                     0   4/28/2022 1:44:00 PM   

                                         INCIDENT_ADDRESS      GEO_X  \
0       128 S CANOSA CT                               ...  3135366.0   
1       650 15TH ST                                   ...  3142454.0   
2       919 E COLFAX AVE                              ...  3147484.0   
3       2345 W ALAMEDA AVE                            ...  3136478.0   
4       7800 E SMITH RD                               ...  3169237.0   
...                                                   ...        ...   
486881  1617 E COLFAX AVE                             ...  3149527.0   
486882  2979 S PONTIAC ST                             ...  3167278.0   
486883  2727 W EVANS AVE                              ...  3134706.0   
486884  1201 16TH ST                                  ...  3141432.0   
486885  3120 W ILIFF AVE                              ...  3132996.0   

            GEO_Y     GEO_LON    GEO_LAT  DISTRICT_ID  PRECINCT_ID  \
0       1685410.0 -105.018825  39.714268          4.0        411.0   
1       1696151.0 -104.993418  39.743649          6.0        611.0   
2       1694898.0 -104.975557  39.740130          6.0        621.0   
3       1684414.0 -105.014892  39.711518          4.0        411.0   
4       1705800.0 -104.897950  39.769688          5.0        512.0   
...           ...         ...        ...          ...          ...   
486881  1694928.0 -104.968291  39.740180          6.0        622.0   
486882  16664

# Drop null values

In [6]:
new_df=df.dropna(axis=1)
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486886 entries, 0 to 486885
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   incident_id             486886 non-null  float64
 1   offense_id              486886 non-null  float64
 2   OFFENSE_CODE            486886 non-null  int64  
 3   OFFENSE_CODE_EXTENSION  486886 non-null  int64  
 4   OFFENSE_TYPE_ID         486886 non-null  object 
 5   OFFENSE_CATEGORY_ID     486886 non-null  object 
 6   FIRST_OCCURRENCE_DATE   486886 non-null  object 
 7   REPORTED_DATE           486886 non-null  object 
 8   IS_CRIME                486886 non-null  int64  
 9   IS_TRAFFIC              486886 non-null  int64  
dtypes: float64(2), int64(4), object(4)
memory usage: 37.1+ MB


In [7]:
new_df.head(10)

incident_id    offense_id  OFFENSE_CODE  OFFENSE_CODE_EXTENSION  \
0  2.022600e+10  2.022600e+16          2999                       0   
1  2.022332e+07  2.022330e+13          2999                       0   
2  2.022309e+07  2.022310e+13          2999                       0   
3  2.022400e+07  2.022400e+13          2999                       0   
4  2.022396e+07  2.022400e+13          2999                       0   
5  2.022390e+07  2.022390e+13          2999                       0   
6  2.022390e+07  2.022390e+13          2999                       0   
7  2.022389e+07  2.022390e+13          2999                       0   
8  2.022808e+07  2.022810e+13          2999                       0   
9  2.022456e+07  2.022460e+13          2999                       0   

           OFFENSE_TYPE_ID OFFENSE_CATEGORY_ID FIRST_OCCURRENCE_DATE  \
0  criminal-mischief-other     public-disorder      01-04-2022 11:30   
1  criminal-mischief-other     public-disorder      01-03-2022 06:45   
2  criminal-mischief-other     public-disorder      01-03-2022 01:00   
3  criminal-mischief-other     public-disorder      01-03-2022 19:47   
4  criminal-mischief-other     public-disorder      01-03-2022 17:06   
5  criminal-mischief-other     public-disorder      01-03-2022 16:40   
6  criminal-mischief-other     public-disorder      01-03-2022 16:19   
7  criminal-mischief-other     public-disorder      01-03-2022 16:15   
8  criminal-mischief-other     public-disorder      01-05-2022 19:00   
9  criminal-mischief-other     public-disorder      01-04-2022 04:30   

      REPORTED_DATE  IS_CRIME  IS_TRAFFIC  
0  01-04-2022 20:36         1           0  
1  01-03-2022 11:01         1           0  
2  01-03-2022 06:11         1           0  
3  01-03-2022 21:12         1           0  
4  01-03-2022 20:31         1           0  
5  01-03-2022 19:07         1           0  
6  01-03-2022 16:21         1           0  
7  01-03-2022 23:05         1           0  
8  01-06-2022 09:03         1           0  
9  01-04-2022 05:09         1           0

In [8]:
new_df.dtypes

incident_id               float64
offense_id                float64
OFFENSE_CODE                int64
OFFENSE_CODE_EXTENSION      int64
OFFENSE_TYPE_ID            object
OFFENSE_CATEGORY_ID        object
FIRST_OCCURRENCE_DATE      object
REPORTED_DATE              object
IS_CRIME                    int64
IS_TRAFFIC                  int64
dtype: object

# Convert string to float

In [9]:
df['OFFENSE_TYPE_ID']= pd.to_numeric(df['OFFENSE_TYPE_ID'], errors='coerce')
df['OFFENSE_CATEGORY_ID']= pd.to_numeric(df['OFFENSE_CATEGORY_ID'], errors='coerce')
df['FIRST_OCCURRENCE_DATE']= pd.to_numeric(df['FIRST_OCCURRENCE_DATE'], errors='coerce')
df['REPORTED_DATE']= pd.to_numeric(df['REPORTED_DATE'], errors='coerce')

In [10]:
new_df.head(10)

incident_id    offense_id  OFFENSE_CODE  OFFENSE_CODE_EXTENSION  \
0  2.022600e+10  2.022600e+16          2999                       0   
1  2.022332e+07  2.022330e+13          2999                       0   
2  2.022309e+07  2.022310e+13          2999                       0   
3  2.022400e+07  2.022400e+13          2999                       0   
4  2.022396e+07  2.022400e+13          2999                       0   
5  2.022390e+07  2.022390e+13          2999                       0   
6  2.022390e+07  2.022390e+13          2999                       0   
7  2.022389e+07  2.022390e+13          2999                       0   
8  2.022808e+07  2.022810e+13          2999                       0   
9  2.022456e+07  2.022460e+13          2999                       0   

           OFFENSE_TYPE_ID OFFENSE_CATEGORY_ID FIRST_OCCURRENCE_DATE  \
0  criminal-mischief-other     public-disorder      01-04-2022 11:30   
1  criminal-mischief-other     public-disorder      01-03-2022 06:45   
2  criminal-mischief-other     public-disorder      01-03-2022 01:00   
3  criminal-mischief-other     public-disorder      01-03-2022 19:47   
4  criminal-mischief-other     public-disorder      01-03-2022 17:06   
5  criminal-mischief-other     public-disorder      01-03-2022 16:40   
6  criminal-mischief-other     public-disorder      01-03-2022 16:19   
7  criminal-mischief-other     public-disorder      01-03-2022 16:15   
8  criminal-mischief-other     public-disorder      01-05-2022 19:00   
9  criminal-mischief-other     public-disorder      01-04-2022 04:30   

      REPORTED_DATE  IS_CRIME  IS_TRAFFIC  
0  01-04-2022 20:36         1           0  
1  01-03-2022 11:01         1           0  
2  01-03-2022 06:11         1           0  
3  01-03-2022 21:12         1           0  
4  01-03-2022 20:31         1           0  
5  01-03-2022 19:07         1           0  
6  01-03-2022 16:21         1           0  
7  01-03-2022 23:05         1           0  
8  01-06-2022 09:03         1           0  
9  01-04-2022 05:09         1           0

# Label Encoder

In [11]:
new_df['OFFENSE_CATEGORY_ID'].unique()

array(['public-disorder', 'drug-alcohol', 'sexual-assault',
       'all-other-crimes', 'traffic-accident', 'robbery',
       'other-crimes-against-persons', 'aggravated-assault', 'arson',
       'burglary', 'larceny', 'theft-from-motor-vehicle', 'auto-theft',
       'white-collar-crime', 'murder'], dtype=object)

In [12]:
lbl_encode=LabelEncoder()
new_df['OFFENSE_TYPE_ID']=lbl_encode.fit_transform(new_df['OFFENSE_TYPE_ID'])
new_df['OFFENSE_CATEGORY_ID']=lbl_encode.fit_transform(new_df['OFFENSE_CATEGORY_ID'])
new_df['FIRST_OCCURRENCE_DATE']=lbl_encode.fit_transform(new_df['FIRST_OCCURRENCE_DATE'])
new_df['REPORTED_DATE']=lbl_encode.fit_transform(new_df['REPORTED_DATE'])


C:\Users\malak\AppData\Local\Temp/ipykernel_11904/1852858910.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['OFFENSE_TYPE_ID']=lbl_encode.fit_transform(new_df['OFFENSE_TYPE_ID'])
C:\Users\malak\AppData\Local\Temp/ipykernel_11904/1852858910.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['OFFENSE_CATEGORY_ID']=lbl_encode.fit_transform(new_df['OFFENSE_CATEGORY_ID'])
C:\Users\malak\AppData\Local\Temp/ipykernel_11904/1852858910.py:4: SettingWithCopyWarning: 
A value is trying to be set on

In [13]:
new_df

incident_id    offense_id  OFFENSE_CODE  OFFENSE_CODE_EXTENSION  \
0       2.022600e+10  2.022600e+16          2999                       0   
1       2.022332e+07  2.022330e+13          2999                       0   
2       2.022309e+07  2.022310e+13          2999                       0   
3       2.022400e+07  2.022400e+13          2999                       0   
4       2.022396e+07  2.022400e+13          2999                       0   
...              ...           ...           ...                     ...   
486881  2.022211e+09  2.022210e+15          2501                       0   
486882  2.022211e+09  2.022210e+15          2604                       1   
486883  2.022212e+09  2.022210e+15          2605                       0   
486884  2.022601e+10  2.022600e+16          2605                       0   
486885  2.022211e+09  2.022210e+15          2607                       0   

        OFFENSE_TYPE_ID  OFFENSE_CATEGORY_ID  FIRST_OCCURRENCE_DATE  \
0                    34                    9                   3604   
1                    34                    9                   2594   
2                    34                    9                   2569   
3                    34                    9                   2689   
4                    34                    9                   2668   
...                 ...                  ...                    ...   
486881               74                   14                 240036   
486882               82                   14                 261806   
486883              170                   14                 236128   
486884              170                   14                 240122   
486885               80                   14                 239058   

        REPORTED_DATE  IS_CRIME  IS_TRAFFIC  
0                4478         1           0  
1                3034         1           0  
2                2993         1           0  
3                3175         1           0  
4                3170         1           0  
...               ...       ...         ...  
486881         307539         1           0  
486882         307564         1           0  
486883         307574         1           0  
486884         306211         1           0  
486885         307541         1           0  

[486886 rows x 10 columns]

In [14]:
lbl_encode=LabelEncoder()
lbl_encode.fit_transform(new_df['OFFENSE_CATEGORY_ID'])

array([ 9,  9,  9, ..., 14, 14, 14], dtype=int64)

In [15]:
lbl_encode=LabelEncoder()
lbl_encode.fit_transform(new_df['FIRST_OCCURRENCE_DATE'])

array([  3604,   2594,   2569, ..., 236128, 240122, 239058], dtype=int64)

In [16]:
lbl_encode=LabelEncoder()
lbl_encode.fit_transform(new_df['REPORTED_DATE'])

array([  4478,   3034,   2993, ..., 307574, 306211, 307541], dtype=int64)

In [17]:
new_df.head(10)

incident_id    offense_id  OFFENSE_CODE  OFFENSE_CODE_EXTENSION  \
0  2.022600e+10  2.022600e+16          2999                       0   
1  2.022332e+07  2.022330e+13          2999                       0   
2  2.022309e+07  2.022310e+13          2999                       0   
3  2.022400e+07  2.022400e+13          2999                       0   
4  2.022396e+07  2.022400e+13          2999                       0   
5  2.022390e+07  2.022390e+13          2999                       0   
6  2.022390e+07  2.022390e+13          2999                       0   
7  2.022389e+07  2.022390e+13          2999                       0   
8  2.022808e+07  2.022810e+13          2999                       0   
9  2.022456e+07  2.022460e+13          2999                       0   

   OFFENSE_TYPE_ID  OFFENSE_CATEGORY_ID  FIRST_OCCURRENCE_DATE  REPORTED_DATE  \
0               34                    9                   3604           4478   
1               34                    9                   2594           3034   
2               34                    9                   2569           2993   
3               34                    9                   2689           3175   
4               34                    9                   2668           3170   
5               34                    9                   2664           3156   
6               34                    9                   2661           3121   
7               34                    9                   2660           3188   
8               34                    9                   4569           6658   
9               34                    9                   3562           4286   

   IS_CRIME  IS_TRAFFIC  
0         1           0  
1         1           0  
2         1           0  
3         1           0  
4         1           0  
5         1           0  
6         1           0  
7         1           0  
8         1           0  
9         1           0

# Test and Split

In [18]:
x=new_df.drop("OFFENSE_CATEGORY_ID",axis=1)
y=new_df["OFFENSE_CATEGORY_ID"]

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

print(len(y_train))
print(len(y_test))


389508
97378


# Decision Tree Classifier

In [20]:
from sklearn import tree
dt_clf=tree.DecisionTreeClassifier(max_depth=5)
dt_clf.fit(x_train, y_train)
dt_clf.score(x_test, y_test)

y_pred= dt_clf.predict(x_test)
dt_clf.score(x_test, y_test)


0.8857647517919859

In [21]:
#Accuracy= accuracy_score(y_test, y_pred) 
#Kappa= cohen_kappa_score(y_test, y_pred)
#Accuracy, Kappa

In [22]:
#y_pred= dt_clf.predict(x_test)
#from sklearn.metrics import confusion_matrix
#confusion_matrix(y_test, y_pred)

In [23]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold Cross validation

In [24]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dt_clf, x, y, cv=10)
scores

array([0.7624104 , 0.82821582, 0.87627596, 0.93368112, 0.93854875,
       0.94349853, 0.87629395, 0.93337167, 0.84004272, 0.83733158])

In [25]:
print(np.mean(scores))

0.8769670501343787


In [26]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 51.67111587524414


In [27]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Stratified Cross Validation

In [28]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(dt_clf, x,y, cv=skfold)


In [29]:
print(np.mean(outcome))

0.8769670501343787


In [30]:
outcome

array([0.7624104 , 0.82821582, 0.87627596, 0.93368112, 0.93854875,
       0.94349853, 0.87629395, 0.93337167, 0.84004272, 0.83733158])

In [31]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 58.09089374542236


In [32]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Repeated Random Train-Test Splits

In [33]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(dt_clf,x,y,cv=ssplit)

In [34]:
results

array([0.88545589, 0.88446319, 0.88529843, 0.88293648, 0.8837101 ,
       0.88364849, 0.88313502, 0.88311448, 0.8845248 , 0.88386072])

In [35]:
print(np.mean(results))

0.8840147604507551


In [36]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 33.21608304977417


# Random Forest Classifier

In [37]:
from sklearn import ensemble
rf_clf= ensemble.RandomForestClassifier(n_estimators=100)
rf_clf.fit(x_train, y_train)
rf_clf.score(x_train, y_train)

1.0

In [38]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold Cross validation

In [39]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(rf_clf, x, y, cv=10)
scores

array([0.97178007, 0.999199  , 0.99932223, 1.        , 1.        ,
       1.        , 0.98899113, 0.99979461, 0.99827473, 0.94840618])

In [40]:
print(np.mean(scores))

0.9905767944846777


In [42]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 950.7967915534973


In [43]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Stratified Cross Validation

In [44]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(rf_clf, x,y, cv=skfold)


In [45]:
print(np.mean(outcome))

0.9901988932677102


In [47]:
outcome

array([0.97399823, 0.99874715, 0.99010043, 1.        , 1.        ,
       1.        , 0.98798472, 0.99993838, 0.99893198, 0.95228804])

In [48]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 827.8878796100616


In [49]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Repeated Random Train-Test Splits

In [50]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(rf_clf,x,y,cv=ssplit)

In [51]:
results

array([0.99994523, 0.99997262, 0.99997262, 0.99996577, 0.99998631,
       0.99996577, 0.99997262, 0.99993838, 0.99994523, 0.99992469])

In [52]:
print(np.mean(results))

0.999958922678789


In [54]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 767.1210119724274


# Naive Bayes Classifier

In [55]:
from sklearn.naive_bayes import GaussianNB
nb_clf= GaussianNB()
nb_clf.fit(x_train, y_train)
nb_clf.score(x_train, y_train)

0.1494860182589318

In [56]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold Cross validation

In [57]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(nb_clf, x, y, cv=10)
scores

array([0.16825156, 0.16165869, 0.1701411 , 0.16436978, 0.13674547,
       0.13939494, 0.16008051, 0.14572379, 0.14247864, 0.14701775])

In [58]:
print(np.mean(scores))

0.15358622132450886


In [59]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 13.342898607254028


In [60]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Stratified Cross Validation

In [61]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(nb_clf, x,y, cv=skfold)


In [62]:
print(np.mean(outcome))

0.15358622132450886


In [63]:
outcome

array([0.16825156, 0.16165869, 0.1701411 , 0.16436978, 0.13674547,
       0.13939494, 0.16008051, 0.14572379, 0.14247864, 0.14701775])

In [64]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 22.161850452423096


In [65]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Repeated Random Train-Test Splits

In [66]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(nb_clf,x,y,cv=ssplit)

In [67]:
results

array([0.15081538, 0.15354703, 0.14953514, 0.15032246, 0.15030192,
       0.14985007, 0.15113031, 0.15063738, 0.1484329 , 0.28505607])

In [68]:
print(np.mean(results))

0.1639628661016253


In [69]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 24.305767059326172


# K-Nearest Neighbour Classifier

In [70]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf= KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(x_train, y_train)
knn_clf.score(x_train, y_train)

0.7712550191523666

In [71]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold cross validation

In [72]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(knn_clf, x, y, cv=10)
scores

array([0.53856107, 0.5256218 , 0.50530921, 0.47797244, 0.48596192,
       0.4540656 , 0.48231597, 0.47905028, 0.50679839, 0.29391226])

In [73]:
print(np.mean(scores))

0.4749568939121727


In [74]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 121.05530571937561


In [75]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Stratified Cross Validation

In [76]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(knn_clf, x,y, cv=skfold)


In [77]:
print(np.mean(outcome))

0.4749568939121727


In [78]:
outcome

array([0.53856107, 0.5256218 , 0.50530921, 0.47797244, 0.48596192,
       0.4540656 , 0.48231597, 0.47905028, 0.50679839, 0.29391226])

In [79]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 134.65222644805908


In [80]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Repeated Random Train-Test Splits

In [81]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(knn_clf,x,y,cv=ssplit)

In [82]:
results

array([0.56566894, 0.56343023, 0.56660688, 0.56757219, 0.56577848,
       0.56397108, 0.56498432, 0.5671135 , 0.56579218, 0.56462832])

In [83]:
print(np.mean(results))

0.56555461229855


In [84]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 183.83489966392517


# Logistic Regression Classifier

In [85]:
from sklearn.linear_model import LogisticRegression
lr_clf= LogisticRegression()
lr_clf.fit(x_train, y_train)
lr_clf.score(x_train, y_train)

0.10722757940786838

In [86]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold cross validation

In [87]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(lr_clf, x, y, cv=10)
scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.10739592, 0.10739592, 0.10739592, 0.10739592, 0.10739592,
       0.10739592, 0.10739813, 0.10739813, 0.10739813, 0.10739813])

In [88]:
print(np.mean(scores))

0.10739680336935939


In [90]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 945.7310492992401


In [91]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Stratified Cross Validation

In [92]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(lr_clf, x,y, cv=skfold)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [93]:
print(np.mean(outcome))

0.10739680336935939


In [94]:
outcome

array([0.10739592, 0.10739592, 0.10739592, 0.10739592, 0.10739592,
       0.10739592, 0.10739813, 0.10739813, 0.10739813, 0.10739813])

In [95]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 430.10534477233887


In [96]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Repeated Random Train-Test Splits

In [97]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(lr_clf,x,y,cv=ssplit)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [98]:
results

array([0.10864951, 0.10726658, 0.10615064, 0.10845097, 0.10927252,
       0.10551395, 0.10702696, 0.10710227, 0.1073145 , 0.10883436])

In [99]:
print(np.mean(results))

0.10755822710281653


In [100]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 365.6485426425934
