# Load Data

In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
%matplotlib inline
from sklearn.metrics import accuracy_score, cohen_kappa_score

# Import data

In [66]:
df=pd.read_csv('Dataset 1.csv')
df=pd.read_csv('Dataset 1.csv')


In [67]:
df.head()

incident_id case_number       incident_datetime  \
0    100068327    12-02555  02/10/2012 10:46:00 AM   
1    100068328    12-02654  02/11/2012 10:14:00 PM   
2    100068329    12-02598  02/10/2012 05:51:00 PM   
3    100068331    12-02535  02/09/2012 10:18:00 PM   
4    100068332    12-02556  02/10/2012 11:19:00 AM   

                       incident_type_primary  \
0   [CTPD]-THEFT - $50 TO $200 - AUTO ACCESS   
1           [CTPD]-ACCIDENT - NON REPORTABLE   
2      [CTPD]-THEFT - $200 AND OVER - RETAIL   
3  [CTPD]-BURGLARY - FORCE - RESIDENCE - UNK   
4              [CTPD]-FRAUD - IDENTITY THEFT   

                 incident_description  clearance_type  \
0   THEFT - $50 TO $200 - AUTO ACCESS             NaN   
1           ACCIDENT - NON REPORTABLE             NaN   
2      THEFT - $200 AND OVER - RETAIL             NaN   
3  BURGLARY - FORCE - RESIDENCE - UNK             NaN   
4              FRAUD - IDENTITY THEFT             NaN   

                      address_1  address_2         city state      zip  \
0  600 Block TOOKANY CREEK PKWY        NaN   CHELTENHAM    PA  19012.0   
1          200 Block BICKLEY RD        NaN      WYNCOTE    PA  19038.0   
2        2400 Block SHOPPERS LN        NaN      WYNCOTE    PA  19095.0   
3     600 Block MEETINGHOUSE RD        NaN  ELKINS PARK    PA      NaN   
4          1 Block LIMEKILN TPK        NaN     GLENSIDE    PA  19038.0   

   country   latitude  longitude              created_at  \
0      NaN  40.068875 -75.121003  02/21/2012 03:15:04 PM   
1      NaN  40.097921 -75.154642  02/21/2012 03:15:04 PM   
2      NaN  40.076851 -75.154990  02/21/2012 03:15:04 PM   
3      NaN  40.085155 -75.124921  02/21/2012 03:15:04 PM   
4      NaN  40.106723 -75.163022  02/21/2012 03:15:04 PM   

               updated_at                      location  hour_of_day  \
0  02/21/2012 03:15:06 PM  POINT (-75.121003 40.068875)           10   
1  02/21/2012 03:15:07 PM  POINT (-75.154642 40.097921)           22   
2  02/21/2012 03:15:07 PM   POINT (-75.15499 40.076851)           17   
3  02/21/2012 03:15:07 PM  POINT (-75.124921 40.085155)           22   
4  02/21/2012 03:15:07 PM  POINT (-75.163022 40.106723)           11   

  day_of_week parent_incident_type  
0      Friday   Theft from Vehicle  
1    Saturday              Traffic  
2      Friday                Theft  
3    Thursday  Breaking & Entering  
4      Friday                Theft

In [68]:
df.isnull().sum()

incident_id                  0
case_number                  0
incident_datetime            0
incident_type_primary        0
incident_description         0
clearance_type           26864
address_1                  220
address_2                26864
city                       101
state                      104
zip                       4536
country                  26864
latitude                   117
longitude                  117
created_at                 184
updated_at                   4
location                   264
hour_of_day                  0
day_of_week                  0
parent_incident_type         0
dtype: int64

In [69]:
for col in df:
    print (type(df[col][1]))

<class 'numpy.int64'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.float64'>
<class 'str'>
<class 'numpy.float64'>
<class 'str'>
<class 'str'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'str'>
<class 'str'>


In [70]:
#data = df.drop(['clearance_type', 'address_2', 'country'], axis=1)

In [71]:
df.head()

incident_id case_number       incident_datetime  \
0    100068327    12-02555  02/10/2012 10:46:00 AM   
1    100068328    12-02654  02/11/2012 10:14:00 PM   
2    100068329    12-02598  02/10/2012 05:51:00 PM   
3    100068331    12-02535  02/09/2012 10:18:00 PM   
4    100068332    12-02556  02/10/2012 11:19:00 AM   

                       incident_type_primary  \
0   [CTPD]-THEFT - $50 TO $200 - AUTO ACCESS   
1           [CTPD]-ACCIDENT - NON REPORTABLE   
2      [CTPD]-THEFT - $200 AND OVER - RETAIL   
3  [CTPD]-BURGLARY - FORCE - RESIDENCE - UNK   
4              [CTPD]-FRAUD - IDENTITY THEFT   

                 incident_description  clearance_type  \
0   THEFT - $50 TO $200 - AUTO ACCESS             NaN   
1           ACCIDENT - NON REPORTABLE             NaN   
2      THEFT - $200 AND OVER - RETAIL             NaN   
3  BURGLARY - FORCE - RESIDENCE - UNK             NaN   
4              FRAUD - IDENTITY THEFT             NaN   

                      address_1  address_2         city state      zip  \
0  600 Block TOOKANY CREEK PKWY        NaN   CHELTENHAM    PA  19012.0   
1          200 Block BICKLEY RD        NaN      WYNCOTE    PA  19038.0   
2        2400 Block SHOPPERS LN        NaN      WYNCOTE    PA  19095.0   
3     600 Block MEETINGHOUSE RD        NaN  ELKINS PARK    PA      NaN   
4          1 Block LIMEKILN TPK        NaN     GLENSIDE    PA  19038.0   

   country   latitude  longitude              created_at  \
0      NaN  40.068875 -75.121003  02/21/2012 03:15:04 PM   
1      NaN  40.097921 -75.154642  02/21/2012 03:15:04 PM   
2      NaN  40.076851 -75.154990  02/21/2012 03:15:04 PM   
3      NaN  40.085155 -75.124921  02/21/2012 03:15:04 PM   
4      NaN  40.106723 -75.163022  02/21/2012 03:15:04 PM   

               updated_at                      location  hour_of_day  \
0  02/21/2012 03:15:06 PM  POINT (-75.121003 40.068875)           10   
1  02/21/2012 03:15:07 PM  POINT (-75.154642 40.097921)           22   
2  02/21/2012 03:15:07 PM   POINT (-75.15499 40.076851)           17   
3  02/21/2012 03:15:07 PM  POINT (-75.124921 40.085155)           22   
4  02/21/2012 03:15:07 PM  POINT (-75.163022 40.106723)           11   

  day_of_week parent_incident_type  
0      Friday   Theft from Vehicle  
1    Saturday              Traffic  
2      Friday                Theft  
3    Thursday  Breaking & Entering  
4      Friday                Theft

In [72]:
new_df= df.fillna(0)
new_df

incident_id case_number       incident_datetime  \
0        100068327    12-02555  02/10/2012 10:46:00 AM   
1        100068328    12-02654  02/11/2012 10:14:00 PM   
2        100068329    12-02598  02/10/2012 05:51:00 PM   
3        100068331    12-02535  02/09/2012 10:18:00 PM   
4        100068332    12-02556  02/10/2012 11:19:00 AM   
...            ...         ...                     ...   
26859    831119768    17-27099  12/13/2017 07:07:00 PM   
26860    831119690    17-27100  12/13/2017 07:34:00 PM   
26861    831119767    17-27102  12/13/2017 08:10:00 PM   
26862    831119961    18-00404  01/09/2018 10:08:00 PM   
26863    831119719    18-00475  01/10/2018 07:09:00 PM   

                           incident_type_primary  \
0       [CTPD]-THEFT - $50 TO $200 - AUTO ACCESS   
1               [CTPD]-ACCIDENT - NON REPORTABLE   
2          [CTPD]-THEFT - $200 AND OVER - RETAIL   
3      [CTPD]-BURGLARY - FORCE - RESIDENCE - UNK   
4                  [CTPD]-FRAUD - IDENTITY THEFT   
...                                          ...   
26859           [CTPD]-ACCIDENT - NON REPORTABLE   
26860                [CTPD]-VEHICLE THEFT - AUTO   
26861      [CTPD]-THEFT - $200 AND OVER - RETAIL   
26862           [CTPD]-ACCIDENT - NON REPORTABLE   
26863  [CTPD]-VANDALISM/CRIM MISCHIEF - VEHICLES   

                     incident_description  clearance_type  \
0       THEFT - $50 TO $200 - AUTO ACCESS             0.0   
1               ACCIDENT - NON REPORTABLE             0.0   
2          THEFT - $200 AND OVER - RETAIL             0.0   
3      BURGLARY - FORCE - RESIDENCE - UNK             0.0   
4                  FRAUD - IDENTITY THEFT             0.0   
...                                   ...             ...   
26859           ACCIDENT - NON REPORTABLE             0.0   
26860                VEHICLE THEFT - AUTO             0.0   
26861      THEFT - $200 AND OVER - RETAIL             0.0   
26862           ACCIDENT - NON REPORTABLE             0.0   
26863  VANDALISM/CRIM MISCHIEF - VEHICLES             0.0   

                              address_1  address_2         city state  \
0          600 Block TOOKANY CREEK PKWY        0.0   CHELTENHAM    PA   
1                  200 Block BICKLEY RD        0.0      WYNCOTE    PA   
2                2400 Block SHOPPERS LN        0.0      WYNCOTE    PA   
3             600 Block MEETINGHOUSE RD        0.0  ELKINS PARK    PA   
4                  1 Block LIMEKILN TPK        0.0     GLENSIDE    PA   
...                                 ...        ...          ...   ...   
26859          EASTON RD & LIMEKILN TPK        0.0     GLENSIDE    PA   
26860      7700 Block LUCRETIA MOTT WAY        0.0  ELKINS PARK    PA   
26861       3000 Block W CHELTENHAM AVE        0.0      WYNCOTE    PA   
26862  WASHINGTON LN & TOWNSHIP LINE RD        0.0  ELKINS PARK    PA   
26863           1900 Block ASHBOURNE RD        0.0  ELKINS PARK    PA   

           zip  country   latitude  longitude              created_at  \
0      19012.0      0.0  40.068875 -75.121003  02/21/2012 03:15:04 PM   
1      19038.0      0.0  40.097921 -75.154642  02/21/2012 03:15:04 PM   
2      19095.0      0.0  40.076851 -75.154990  02/21/2012 03:15:04 PM   
3          0.0      0.0  40.085155 -75.124921  02/21/2012 03:15:04 PM   
4      19038.0      0.0  40.106723 -75.163022  02/21/2012 03:15:04 PM   
...        ...      ...        ...        ...                     ...   
26859  19095.0      0.0  40.092138 -75.162038  01/08/2018 01:05:09 PM   
26860  19027.0      0.0  40.075155 -75.148525  01/08/2018 01:05:09 PM   
26861  19150.0      0.0  40.080281 -75.167319  01/08/2018 01:05:09 PM   
26862  19095.0      0.0  40.089328 -75.131741  01/08/2018 01:05:09 PM   
26863  19027.0      0.0  40.076838 -75.148099  01/08/2018 01:05:09 PM   

                   updated_at                        location  hour_of_day  \
0      02/21/2012 03:15:06 PM    POINT (-75.121003 40.068875)           10   
1      02/21/2012 03:15:07 PM    POINT (-7

In [73]:
#new_df=df.interpolate
#new_df()

# Drop null values

In [74]:
new_df=df.dropna(axis=1)
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26864 entries, 0 to 26863
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   incident_id            26864 non-null  int64 
 1   case_number            26864 non-null  object
 2   incident_datetime      26864 non-null  object
 3   incident_type_primary  26864 non-null  object
 4   incident_description   26864 non-null  object
 5   hour_of_day            26864 non-null  int64 
 6   day_of_week            26864 non-null  object
 7   parent_incident_type   26864 non-null  object
dtypes: int64(2), object(6)
memory usage: 1.6+ MB


In [75]:
new_df.head(10)

incident_id case_number       incident_datetime  \
0    100068327    12-02555  02/10/2012 10:46:00 AM   
1    100068328    12-02654  02/11/2012 10:14:00 PM   
2    100068329    12-02598  02/10/2012 05:51:00 PM   
3    100068331    12-02535  02/09/2012 10:18:00 PM   
4    100068332    12-02556  02/10/2012 11:19:00 AM   
5    100068334    12-02478  02/08/2012 06:16:00 PM   
6    100068335    12-02734  02/13/2012 08:47:00 AM   
7    100068336    12-02614  02/10/2012 10:35:00 PM   
8    100068337    12-02656  02/11/2012 10:36:00 PM   
9    100068338    12-02460  02/08/2012 01:40:00 PM   

                       incident_type_primary  \
0   [CTPD]-THEFT - $50 TO $200 - AUTO ACCESS   
1           [CTPD]-ACCIDENT - NON REPORTABLE   
2      [CTPD]-THEFT - $200 AND OVER - RETAIL   
3  [CTPD]-BURGLARY - FORCE - RESIDENCE - UNK   
4              [CTPD]-FRAUD - IDENTITY THEFT   
5      [CTPD]-THEFT - $50 TO $200 - BICYCLES   
6  [CTPD]-VANDALISM/CRIM MISCHIEF - VEHICLES   
7                  [CTPD]-DISORDERLY CONDUCT   
8  [CTPD]-VANDALISM/CRIM MISCHIEF - VEHICLES   
9                  [CTPD]-DISORDERLY CONDUCT   

                 incident_description  hour_of_day day_of_week  \
0   THEFT - $50 TO $200 - AUTO ACCESS           10      Friday   
1           ACCIDENT - NON REPORTABLE           22    Saturday   
2      THEFT - $200 AND OVER - RETAIL           17      Friday   
3  BURGLARY - FORCE - RESIDENCE - UNK           22    Thursday   
4              FRAUD - IDENTITY THEFT           11      Friday   
5      THEFT - $50 TO $200 - BICYCLES           18   Wednesday   
6  VANDALISM/CRIM MISCHIEF - VEHICLES            8      Monday   
7                  DISORDERLY CONDUCT           22      Friday   
8  VANDALISM/CRIM MISCHIEF - VEHICLES           22    Saturday   
9                  DISORDERLY CONDUCT           13   Wednesday   

  parent_incident_type  
0   Theft from Vehicle  
1              Traffic  
2                Theft  
3  Breaking & Entering  
4                Theft  
5                Theft  
6       Property Crime  
7             Disorder  
8       Property Crime  
9             Disorder

In [76]:
new_df.dtypes

incident_id               int64
case_number              object
incident_datetime        object
incident_type_primary    object
incident_description     object
hour_of_day               int64
day_of_week              object
parent_incident_type     object
dtype: object

# Convert sting values to float

In [77]:
df['case_number']= pd.to_numeric(df['case_number'], errors='coerce')
df['incident_datetime']= pd.to_numeric(df['incident_datetime'], errors='coerce')
df['incident_type_primary']= pd.to_numeric(df['incident_type_primary'], errors='coerce')
df['incident_description']= pd.to_numeric(df['incident_description'], errors='coerce')
df['created_at']= pd.to_numeric(df['created_at'], errors='coerce')
df['updated_at']= pd.to_numeric(df['updated_at'], errors='coerce')
df['address_1']= pd.to_numeric(df['address_1'], errors='coerce')
df['city']= pd.to_numeric(df['city'], errors='coerce')
df['state']= pd.to_numeric(df['state'], errors='coerce')
df['longitude']= pd.to_numeric(df['longitude'], errors='coerce')
df['location']= pd.to_numeric(df['location'], errors='coerce')
df['day_of_week']= pd.to_numeric(df['day_of_week'], errors='coerce')

In [78]:
new_df.dtypes

incident_id               int64
case_number              object
incident_datetime        object
incident_type_primary    object
incident_description     object
hour_of_day               int64
day_of_week              object
parent_incident_type     object
dtype: object

In [79]:
new_df.head(10)

incident_id case_number       incident_datetime  \
0    100068327    12-02555  02/10/2012 10:46:00 AM   
1    100068328    12-02654  02/11/2012 10:14:00 PM   
2    100068329    12-02598  02/10/2012 05:51:00 PM   
3    100068331    12-02535  02/09/2012 10:18:00 PM   
4    100068332    12-02556  02/10/2012 11:19:00 AM   
5    100068334    12-02478  02/08/2012 06:16:00 PM   
6    100068335    12-02734  02/13/2012 08:47:00 AM   
7    100068336    12-02614  02/10/2012 10:35:00 PM   
8    100068337    12-02656  02/11/2012 10:36:00 PM   
9    100068338    12-02460  02/08/2012 01:40:00 PM   

                       incident_type_primary  \
0   [CTPD]-THEFT - $50 TO $200 - AUTO ACCESS   
1           [CTPD]-ACCIDENT - NON REPORTABLE   
2      [CTPD]-THEFT - $200 AND OVER - RETAIL   
3  [CTPD]-BURGLARY - FORCE - RESIDENCE - UNK   
4              [CTPD]-FRAUD - IDENTITY THEFT   
5      [CTPD]-THEFT - $50 TO $200 - BICYCLES   
6  [CTPD]-VANDALISM/CRIM MISCHIEF - VEHICLES   
7                  [CTPD]-DISORDERLY CONDUCT   
8  [CTPD]-VANDALISM/CRIM MISCHIEF - VEHICLES   
9                  [CTPD]-DISORDERLY CONDUCT   

                 incident_description  hour_of_day day_of_week  \
0   THEFT - $50 TO $200 - AUTO ACCESS           10      Friday   
1           ACCIDENT - NON REPORTABLE           22    Saturday   
2      THEFT - $200 AND OVER - RETAIL           17      Friday   
3  BURGLARY - FORCE - RESIDENCE - UNK           22    Thursday   
4              FRAUD - IDENTITY THEFT           11      Friday   
5      THEFT - $50 TO $200 - BICYCLES           18   Wednesday   
6  VANDALISM/CRIM MISCHIEF - VEHICLES            8      Monday   
7                  DISORDERLY CONDUCT           22      Friday   
8  VANDALISM/CRIM MISCHIEF - VEHICLES           22    Saturday   
9                  DISORDERLY CONDUCT           13   Wednesday   

  parent_incident_type  
0   Theft from Vehicle  
1              Traffic  
2                Theft  
3  Breaking & Entering  
4                Theft  
5                Theft  
6       Property Crime  
7             Disorder  
8       Property Crime  
9             Disorder

# Label Encoder

In [80]:

new_df['parent_incident_type'].unique()

array(['Theft from Vehicle', 'Traffic', 'Theft', 'Breaking & Entering',
       'Property Crime', 'Disorder', 'Liquor', 'Community Policing',
       'Assault', 'Weapons Offense', 'Missing Person', 'Drugs',
       'Theft of Vehicle', 'Robbery', 'Assault with Deadly Weapon',
       'Sexual Assault', 'Other', 'Kidnapping', 'Arson',
       'Other Sexual Offense', 'Family Offense', 'Homicide'], dtype=object)

In [81]:
lbl_encode=LabelEncoder()
new_df['day_of_week']=lbl_encode.fit_transform(new_df['day_of_week'])
new_df['parent_incident_type']=lbl_encode.fit_transform(new_df['parent_incident_type'])
new_df['incident_description']=lbl_encode.fit_transform(new_df['incident_description'])
new_df['incident_type_primary']=lbl_encode.fit_transform(new_df['incident_type_primary'])
new_df['incident_datetime']=lbl_encode.fit_transform(new_df['incident_datetime'])
new_df['case_number']=lbl_encode.fit_transform(new_df['case_number'])


C:\Users\malak\AppData\Local\Temp/ipykernel_7364/3963704421.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['day_of_week']=lbl_encode.fit_transform(new_df['day_of_week'])
C:\Users\malak\AppData\Local\Temp/ipykernel_7364/3963704421.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['parent_incident_type']=lbl_encode.fit_transform(new_df['parent_incident_type'])
C:\Users\malak\AppData\Local\Temp/ipykernel_7364/3963704421.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy o

In [82]:
new_df

incident_id  case_number  incident_datetime  incident_type_primary  \
0        100068327         4564               3158                    112   
1        100068328         4586               3245                      1   
2        100068329         4574               3153                    109   
3        100068331         4562               3099                     31   
4        100068332         4565               3159                     64   
...            ...          ...                ...                    ...   
26859    831119768        26152              25274                      1   
26860    831119690        26153              25275                    131   
26861    831119767        26154              25276                    109   
26862    831119961        26391                675                      1   
26863    831119719        26401                751                    129   

       incident_description  hour_of_day  day_of_week  parent_incident_type  
0                       112           10            0                    18  
1                         1           22            2                    20  
2                       109           17            0                    17  
3                        31           22            4                     3  
4                        64           11            0                    17  
...                     ...          ...          ...                   ...  
26859                     1           19            6                    20  
26860                   131           19            6                    19  
26861                   109           20            6                    17  
26862                     1           22            5                    20  
26863                   129           19            6                    14  

[26864 rows x 8 columns]

In [83]:
lbl_encode=LabelEncoder()
lbl_encode.fit_transform(new_df['day_of_week'])

array([0, 2, 0, ..., 6, 5, 6], dtype=int64)

In [84]:
lbl_encode=LabelEncoder()
lbl_encode.fit_transform(new_df['parent_incident_type'])

array([18, 20, 17, ..., 17, 20, 14], dtype=int64)

In [85]:
lbl_encode=LabelEncoder()
lbl_encode.fit_transform(new_df['incident_description'])

array([112,   1, 109, ..., 109,   1, 129], dtype=int64)

In [86]:
new_df.head(10)

incident_id  case_number  incident_datetime  incident_type_primary  \
0    100068327         4564               3158                    112   
1    100068328         4586               3245                      1   
2    100068329         4574               3153                    109   
3    100068331         4562               3099                     31   
4    100068332         4565               3159                     64   
5    100068334         4554               3021                    113   
6    100068335         4602               3396                    129   
7    100068336         4576               3157                     43   
8    100068337         4588               3246                    129   
9    100068338         4551               3018                     43   

   incident_description  hour_of_day  day_of_week  parent_incident_type  
0                   112           10            0                    18  
1                     1           22            2                    20  
2                   109           17            0                    17  
3                    31           22            4                     3  
4                    64           11            0                    17  
5                   113           18            6                    17  
6                   129            8            1                    14  
7                    43           22            0                     5  
8                   129           22            2                    14  
9                    43           13            6                     5

# Train and Split

In [87]:
x=new_df.drop("parent_incident_type",axis=1)
y=new_df["parent_incident_type"]

In [88]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

print(len(y_train))
print(len(y_test))


21491
5373


# Creating & Training Decision Tree Model

In [89]:
from sklearn import tree
dt_clf=tree.DecisionTreeClassifier(max_depth=5)
dt_clf.fit(x_train, y_train)
dt_clf.score(x_test, y_test)

y_pred= dt_clf.predict(x_test)
dt_clf.score(x_test, y_test)


0.8700911967243625

In [90]:
#Accuracy= accuracy_score(y_test, y_pred) 
#Kappa= cohen_kappa_score(y_test, y_pred)
#Accuracy, Kappa

In [91]:
#y_pred= dt_clf.predict(x_test)
#from sklearn.metrics import confusion_matrix
#mat=confusion_matrix(y_test, y_pred)
#mat

In [97]:
accuracy_score(y_test, y_pred)

0.8700911967243625

In [98]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 


# K-fold Cross validation

In [99]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dt_clf, x, y, cv=10)
scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


array([0.8678824 , 0.87346483, 0.87048753, 0.87793078, 0.86969471,
       0.86895011, 0.86857781, 0.87825763, 0.87527923, 0.87192852])

In [100]:
print(np.mean(scores))

0.8722453549688096


In [101]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 9.433733224868774


In [102]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Stratified Cross Validation

In [103]:

skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(dt_clf, x,y, cv=skfold)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


In [104]:
print(np.mean(outcome))

0.8722453549688096


In [105]:
outcome

array([0.8678824 , 0.87346483, 0.87048753, 0.87793078, 0.86969471,
       0.86895011, 0.86857781, 0.87825763, 0.87527923, 0.87192852])

In [106]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 22.437958478927612


In [107]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Repeated Random Train-Test Splits

In [108]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(dt_clf,x,y,cv=ssplit)

In [109]:
print(np.mean(results))

0.8749999999999998


In [110]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 3.652717113494873


# Confusion Matrix

In [111]:
#from sklearn import matrics

In [112]:
#from sklearn.model_selection import cross_val_predict
#pred= cross_val_predict(dt_clf, x_test, y_test)
#pred

In [113]:
#scores_test = cross_val_score(dt_clf, x_train, y_train, scoring='r2', cv=10)
#scores_test

In [114]:
#print(np.mean(scores_test))

# Random Forest Classifier

In [115]:
from sklearn import ensemble
rf_clf= ensemble.RandomForestClassifier(n_estimators=100)
rf_clf.fit(x_train, y_train)
rf_clf.score(x_train, y_train)

1.0

In [116]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# K-fold Cross validation

In [117]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(rf_clf, x, y, cv=10)
scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


array([0.98846297, 0.95906215, 0.97655378, 0.86043915, 0.87862993,
       0.85070737, 0.97915115, 0.97096054, 0.93521966, 0.80528667])

In [118]:
print(np.mean(scores))

0.9204473373771455


In [119]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 47.077614545822144


In [120]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Stratified Cross Validation

In [53]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(rf_clf, x,y, cv=skfold)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


In [54]:
print(np.mean(outcome))

0.9192196175790277


In [55]:
outcome

array([0.98809081, 0.93561593, 0.97543729, 0.8619278 , 0.84698436,
       0.8655994 , 0.98361876, 0.96686523, 0.93521966, 0.83283693])

In [56]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 62.808117628097534


In [57]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Repeated Random Train-Test Splits

In [58]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(dt_clf,x,y,cv=ssplit)

In [59]:
results

array([0.87555831, 0.87282878, 0.87382134, 0.87084367, 0.87171216,
       0.87717122, 0.87320099, 0.87990074, 0.88039702, 0.87158809])

In [60]:
print(np.mean(results))

0.8747022332506204


In [61]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 3.9291210174560547


# Naive Bayes Classifier

In [121]:
from sklearn.naive_bayes import GaussianNB
nb_clf= GaussianNB()
nb_clf.fit(x_train, y_train)
nb_clf.score(x_train, y_train)

0.3882090177283514

In [122]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold Cross validation

In [123]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(nb_clf, x, y, cv=10)
scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


array([0.39039821, 0.39039821, 0.39039821, 0.39039821, 0.39054356,
       0.39054356, 0.39054356, 0.39054356, 0.39054356, 0.39054356])

In [124]:
print(np.mean(scores))

0.3904854209659536


In [125]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 3.703075408935547


In [126]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Stratified Cross Validation

In [127]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(nb_clf, x,y, cv=skfold)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


In [128]:
print(np.mean(outcome))

0.3904854209659536


In [129]:
outcome

array([0.39039821, 0.39039821, 0.39039821, 0.39039821, 0.39054356,
       0.39054356, 0.39054356, 0.39054356, 0.39054356, 0.39054356])

In [130]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 11.124524593353271


In [131]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Repeated Random Train-Test Splits

In [132]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(nb_clf,x,y,cv=ssplit)

In [133]:
results

array([0.38598015, 0.40372208, 0.38808933, 0.38672457, 0.38759305,
       0.38647643, 0.39503722, 0.38436725, 0.39540943, 0.39739454])

In [134]:
print(np.mean(results))

0.39107940446650125


In [135]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 3.3933217525482178


# K-NearestNeighbour Classifier

In [136]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf= KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(x_train, y_train)
knn_clf.score(x_train, y_train)

0.7524545158438416

In [137]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold Cross validation

In [138]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(knn_clf, x, y, cv=10)
scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


array([0.3550428 , 0.29921846, 0.25120953, 0.30554522, 0.33172003,
       0.23678332, 0.1824274 , 0.23864483, 0.2740134 , 0.06329114])

In [139]:
print(np.mean(scores))

0.25378961221135604


In [140]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 6.693057060241699


In [141]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Stratified Cross Validation

In [83]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(knn_clf, x,y, cv=skfold)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


In [84]:
print(np.mean(outcome))

0.25378961221135604


In [85]:
outcome

array([0.3550428 , 0.29921846, 0.25120953, 0.30554522, 0.33172003,
       0.23678332, 0.1824274 , 0.23864483, 0.2740134 , 0.06329114])

In [86]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 32.485968351364136


In [87]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Repeated Random Train-Test Splits

In [88]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(knn_clf,x,y,cv=ssplit)

In [89]:
results

array([0.567866  , 0.55533499, 0.55880893, 0.55111663, 0.55781638,
       0.558933  , 0.55322581, 0.56389578, 0.5528536 , 0.56054591])

In [90]:
print(np.mean(results))

0.5580397022332505


In [91]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 20.105567932128906


# Logistic Regression Classifier

In [92]:
from sklearn.linear_model import LogisticRegression
lr_clf= LogisticRegression()
lr_clf.fit(x_train, y_train)
lr_clf.score(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.3882090177283514

In [93]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()

# K-fold Cross validation

In [94]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(lr_clf, x, y, cv=10)
scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the dat

array([0.39039821, 0.39039821, 0.39039821, 0.39039821, 0.39054356,
       0.39054356, 0.39054356, 0.39054356, 0.39054356, 0.39054356])

In [95]:
print(np.mean(scores))

0.3904854209659536


In [96]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 123.16754484176636


In [97]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Stratified Cross Validation

In [98]:
skfold=StratifiedKFold(n_splits=10)
outcome = cross_val_score(lr_clf, x,y, cv=skfold)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the dat

In [99]:
print(np.mean(outcome))

0.3904854209659536


In [100]:
outcome

array([0.39039821, 0.39039821, 0.39039821, 0.39039821, 0.39054356,
       0.39054356, 0.39054356, 0.39054356, 0.39054356, 0.39054356])

In [101]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 245.62329053878784


In [102]:
import time
 
# we initialize the variable start
# to store the starting time of
# execution of program
start = time.time()
 

# Repeated Random Train-Test Splits

In [103]:
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10, test_size=0.30)
results=cross_val_score(knn_clf,x,y,cv=ssplit)

In [104]:
results

array([0.55260546, 0.55806452, 0.56439206, 0.5560794 , 0.56054591,
       0.55918114, 0.5601737 , 0.55669975, 0.56029777, 0.55372208])

In [105]:
print(np.mean(results))

0.5581761786600496


In [106]:
end = time.time()
 
# difference of start and end variables
# gives the time of execution of the
# program in between
print("The time of execution of above program is :", end-start)

The time of execution of above program is : 11.847171306610107
